project_id = "cwhmxpitwblqxgrvaigg"

[functions.fetch-exchange-rates]
verify_jwt = false

[functions.send-quote-notifications]
verify_jwt = false

[functions.send-quote-status-email]
verify_jwt = false

[functions.admin-products-bulk]
verify_jwt = false